/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface ExtraFieldsItem {
    key: string;
    label?: string;
    value?: Record<string, unknown>;
    present: boolean;
}
