/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface GameComplete {
    completedAt: string;
    didWin?: boolean;
    hints?: number;
    score?: number;
    completionTime?: number;
}
