/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { BuzzshotApi } from "@fern-api/buzzshot";

export interface Group {
    id?: number;
    addedAt?: string;
    updatedAt?: string;
    isEvent?: boolean;
    name?: string;
    date: string;
    time: string;
    startAt?: string;
    games?: BuzzshotApi.Games[];
    players: BuzzshotApi.Player[];
    photos?: BuzzshotApi.PhotosItem[];
}
