/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface ProcessedPhotoDetails {
    addedAt?: string;
    game?: string;
    group?: string;
    photo: string;
    processedImage?: string;
    ready?: string;
}
