/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface ListPlayersRequest {
    /**
     * A page number within the paginated result set.
     */
    page?: number;
}
