/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface ListGroupsRequest {
    /**
     * A page number within the paginated result set.
     */
    page?: number;
    /**
     * is_event
     */
    isEvent?: string;
    /**
     * complete
     */
    complete?: string;
}
