/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface ListGamesRequest {
    /**
     * A page number within the paginated result set.
     */
    page?: number;
    /**
     * complete
     */
    complete?: string;
    /**
     * Date
     */
    date?: string;
    /**
     * Before
     */
    before?: string;
    /**
     * After
     */
    after?: string;
}
