/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface RetrieveGameRequest {
    /**
     * complete
     */
    complete?: string;
    /**
     * Date
     */
    date?: string;
    /**
     * Before
     */
    before?: string;
    /**
     * After
     */
    after?: string;
}
