/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface RetrieveGroupRequest {
    /**
     * is_event
     */
    isEvent?: string;
    /**
     * complete
     */
    complete?: string;
}
