/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import { BuzzshotApi } from "@fern-api/buzzshot";
import * as core from "../../core";

export const GameComplete: core.serialization.ObjectSchema<serializers.GameComplete.Raw, BuzzshotApi.GameComplete> =
    core.serialization.object({
        completedAt: core.serialization.property("completed_at", core.serialization.string()),
        didWin: core.serialization.property("did_win", core.serialization.boolean().optional()),
        hints: core.serialization.number().optional(),
        score: core.serialization.number().optional(),
        completionTime: core.serialization.property("completion_time", core.serialization.number().optional()),
    });

export declare namespace GameComplete {
    interface Raw {
        completed_at: string;
        did_win?: boolean | null;
        hints?: number | null;
        score?: number | null;
        completion_time?: number | null;
    }
}
