/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import { BuzzshotApi } from "@fern-api/buzzshot";
import * as core from "../../core";

export const Games: core.serialization.ObjectSchema<serializers.Games.Raw, BuzzshotApi.Games> =
    core.serialization.object({
        id: core.serialization.number().optional(),
        addedAt: core.serialization.property("added_at", core.serialization.string().optional()),
        updatedAt: core.serialization.property("updated_at", core.serialization.string().optional()),
        name: core.serialization.string().optional(),
        date: core.serialization.string(),
        time: core.serialization.string(),
        startAt: core.serialization.property("start_at", core.serialization.string().optional()),
        room: core.serialization.string().optional(),
        extraFields: core.serialization.property(
            "extra_fields",
            core.serialization.list(core.serialization.lazyObject(async () => (await import("..")).ExtraFieldsItem))
        ),
        complete: core.serialization.lazyObject(async () => (await import("..")).GameComplete),
    });

export declare namespace Games {
    interface Raw {
        id?: number | null;
        added_at?: string | null;
        updated_at?: string | null;
        name?: string | null;
        date: string;
        time: string;
        start_at?: string | null;
        room?: string | null;
        extra_fields: serializers.ExtraFieldsItem.Raw[];
        complete: serializers.GameComplete.Raw;
    }
}
