/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import { BuzzshotApi } from "@fern-api/buzzshot";
import * as core from "../../core";

export const Group: core.serialization.ObjectSchema<serializers.Group.Raw, BuzzshotApi.Group> =
    core.serialization.object({
        id: core.serialization.number().optional(),
        addedAt: core.serialization.property("added_at", core.serialization.string().optional()),
        updatedAt: core.serialization.property("updated_at", core.serialization.string().optional()),
        isEvent: core.serialization.property("is_event", core.serialization.boolean().optional()),
        name: core.serialization.string().optional(),
        date: core.serialization.string(),
        time: core.serialization.string(),
        startAt: core.serialization.property("start_at", core.serialization.string().optional()),
        games: core.serialization
            .list(core.serialization.lazyObject(async () => (await import("..")).Games))
            .optional(),
        players: core.serialization.list(core.serialization.lazyObject(async () => (await import("..")).Player)),
        photos: core.serialization
            .list(core.serialization.lazyObject(async () => (await import("..")).PhotosItem))
            .optional(),
    });

export declare namespace Group {
    interface Raw {
        id?: number | null;
        added_at?: string | null;
        updated_at?: string | null;
        is_event?: boolean | null;
        name?: string | null;
        date: string;
        time: string;
        start_at?: string | null;
        games?: serializers.Games.Raw[] | null;
        players: serializers.Player.Raw[];
        photos?: serializers.PhotosItem.Raw[] | null;
    }
}
