/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import { BuzzshotApi } from "@fern-api/buzzshot";
import * as core from "../../core";

export const PhotosItem: core.serialization.ObjectSchema<serializers.PhotosItem.Raw, BuzzshotApi.PhotosItem> =
    core.serialization.object({
        addedAt: core.serialization.property("added_at", core.serialization.string().optional()),
        photo: core.serialization.string(),
        processedImage: core.serialization.property("processed_image", core.serialization.string().optional()),
        ready: core.serialization.string().optional(),
    });

export declare namespace PhotosItem {
    interface Raw {
        added_at?: string | null;
        photo: string;
        processed_image?: string | null;
        ready?: string | null;
    }
}
