/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import { BuzzshotApi } from "@fern-api/buzzshot";
import * as core from "../../core";

export const Player: core.serialization.ObjectSchema<serializers.Player.Raw, BuzzshotApi.Player> =
    core.serialization.object({
        addedAt: core.serialization.property("added_at", core.serialization.string().optional()),
        updatedAt: core.serialization.property("updated_at", core.serialization.string().optional()),
        player: core.serialization.string().optional(),
        firstName: core.serialization.property("first_name", core.serialization.string().optional()),
        lastName: core.serialization.property("last_name", core.serialization.string().optional()),
        email: core.serialization.string(),
        phone: core.serialization.string(),
        extraFields: core.serialization.property(
            "extra_fields",
            core.serialization.list(core.serialization.lazyObject(async () => (await import("..")).ExtraFieldsItem))
        ),
        signature: core.serialization.string().optional(),
    });

export declare namespace Player {
    interface Raw {
        added_at?: string | null;
        updated_at?: string | null;
        player?: string | null;
        first_name?: string | null;
        last_name?: string | null;
        email: string;
        phone: string;
        extra_fields: serializers.ExtraFieldsItem.Raw[];
        signature?: string | null;
    }
}
