/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import { BuzzshotApi } from "@fern-api/buzzshot";
import * as core from "../../core";

export const ProcessedPhotoDetails: core.serialization.ObjectSchema<
    serializers.ProcessedPhotoDetails.Raw,
    BuzzshotApi.ProcessedPhotoDetails
> = core.serialization.object({
    addedAt: core.serialization.property("added_at", core.serialization.string().optional()),
    game: core.serialization.string().optional(),
    group: core.serialization.string().optional(),
    photo: core.serialization.string(),
    processedImage: core.serialization.property("processed_image", core.serialization.string().optional()),
    ready: core.serialization.string().optional(),
});

export declare namespace ProcessedPhotoDetails {
    interface Raw {
        added_at?: string | null;
        game?: string | null;
        group?: string | null;
        photo: string;
        processed_image?: string | null;
        ready?: string | null;
    }
}
