/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import { BuzzshotApi } from "@fern-api/buzzshot";
import * as core from "../../core";

export const Room: core.serialization.ObjectSchema<serializers.Room.Raw, BuzzshotApi.Room> = core.serialization.object({
    id: core.serialization.number().optional(),
    name: core.serialization.string(),
    hidden: core.serialization.boolean().optional(),
});

export declare namespace Room {
    interface Raw {
        id?: number | null;
        name: string;
        hidden?: boolean | null;
    }
}
